THIS CHART WAS MADE WITH THE INTENTION TO BE AUTOMATED. PLEASE CLICK ON THE DEEPNOTE LINK.

The Kaggle dataset is too large to be pushed into Github and so needs to be filtered in Python. Another limiationan is that it is not read in Vegalite as it is not a raw csv file. Therefore, the dataset has to be filtered in Python, then hosted remotely and finally read in Vegalite to make the chart.

In [66]:
import pandas as pd
import numpy as np
import requests
#To set the size of a dataframe in Python.
pd.set_option('display.max_rows', 800)
pd.set_option('display.max_columns', 800)

In [67]:
#Reference: https://www.google.com/covid19/mobility/
#Data comes from Kaggle https://www.kaggle.com/devinaconley/covid19-mobility-data
df = pd.read_csv(r'https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv')
df

C:\Users\vw191\Downloads\annaconda\lib\site-packages\IPython\core\interactiveshell.py:3343: DtypeWarning: Columns (3,4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,AE,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,ChIJvRKrsd9IXj4RpwoIwFYv0zM,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8378151,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,NaN,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-01-05,NaN,NaN,NaN,NaN,34.0,NaN
8378152,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,NaN,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-01-06,NaN,NaN,NaN,NaN,36.0,NaN
8378153,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,NaN,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-01-07,NaN,NaN,NaN,NaN,38.0,NaN
8378154,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,NaN,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-01-10,NaN,NaN,NaN,NaN,33.0,NaN
8378155,ZW,Zimbabwe,Midlands Province,Kwekwe,NaN,NaN,NaN,ChIJRcIZ3-FJNBkRRsj55IcLpfU,2022-01-11,NaN,NaN,NaN,NaN,40.0,NaN

In [68]:
df['sub_region_1'][df['country_region']=='United Kingdom'].unique() #Checking to see the sub regions for the UK.

array([nan, 'Aberdeen City', 'Aberdeenshire', 'Angus Council',
       'Antrim and Newtownabbey', 'Ards and North Down',
       'Argyll and Bute Council', 'Armagh City, Banbridge and Craigavon',
       'Bath and North East Somerset', 'Bedford', 'Belfast',
       'Blackburn with Darwen', 'Blackpool', 'Blaenau Gwent',
       'Borough of Halton', 'Bracknell Forest', 'Bridgend County Borough',
       'Brighton and Hove', 'Bristol City', 'Buckinghamshire',
       'Caerphilly County Borough', 'Cambridgeshire', 'Cardiff',
       'Carmarthenshire', 'Causeway Coast and Glens',
       'Central Bedfordshire', 'Ceredigion', 'Cheshire East',
       'Cheshire West and Chester', 'Clackmannanshire',
       'Conwy Principal Area', 'Cornwall', 'County Durham', 'Cumbria',
       'Darlington', 'Denbighshire', 'Derby', 'Derbyshire',
       'Derry and Strabane', 'Devon', 'Dorset', 'Dumfries and Galloway',
       'Dundee City Council', 'East Ayrshire Council',
       'East Dunbartonshire Council', 'East Lothian Council',
       'East Renfrewshire Council', 'East Riding of Yorkshire',
       'East Sussex', 'Edinburgh', 'Essex', 'Falkirk',
       'Fermanagh and Omagh', 'Fife', 'Flintshire', 'Glasgow City',
       'Gloucestershire', 'Greater London', 'Greater Manchester',
       'Gwynedd', 'Hampshire', 'Hartlepool', 'Herefordshire',
       'Hertfordshire', 'Highland Council', 'Inverclyde',
       'Isle of Anglesey', 'Isle of Wight', 'Kent', 'Kingston upon Hull',
       'Lancashire', 'Leicester', 'Leicestershire', 'Lincolnshire',
       'Lisburn and Castlereagh', 'Luton', 'Medway', 'Merseyside',
       'Merthyr Tydfil County Borough', 'Mid and East Antrim',
       'Mid Ulster', 'Middlesbrough', 'Midlothian', 'Milton Keynes',
       'Monmouthshire', 'Moray', 'Na h-Eileanan an Iar',
       'Neath Port Talbot Principle Area', 'Newport',
       'Newry, Mourne and Down', 'Norfolk', 'North Ayrshire Council',
       'North East Lincolnshire', 'North Lanarkshire',
       'North Lincolnshire', 'North Somerset', 'North Yorkshire',
       'Northamptonshire', 'Northumberland', 'Nottingham',
       'Nottinghamshire', 'Orkney', 'Oxfordshire', 'Pembrokeshire',
       'Perth and Kinross', 'Peterborough', 'Plymouth', 'Portsmouth',
       'Powys', 'Reading', 'Redcar and Cleveland', 'Renfrewshire',
       'Rhondda Cynon Taff', 'Rutland', 'Scottish Borders',
       'Shetland Islands', 'Shropshire', 'Slough', 'Somerset',
       'South Ayrshire Council', 'South Gloucestershire',
       'South Lanarkshire', 'South Yorkshire', 'Southampton',
       'Southend-on-Sea', 'Staffordshire', 'Stirling', 'Stockton-on-Tees',
       'Stoke-on-Trent', 'Suffolk', 'Surrey', 'Swansea', 'Swindon',
       'Thurrock', 'Torbay', 'Torfaen Principal Area', 'Tyne and Wear',
       'Vale of Glamorgan', 'Warrington', 'Warwickshire',
       'West Berkshire', 'West Dunbartonshire Council', 'West Lothian',
       'West Midlands', 'West Sussex', 'West Yorkshire', 'Wiltshire',
       'Windsor and Maidenhead', 'Wokingham', 'Worcestershire',
       'Wrexham Principal Area', 'York'], dtype=object)

In [69]:
dfuk = df[df['country_region']=='United Kingdom'] # Filtered for the UK

In [70]:
dfuk.columns.unique() #All column names are lower case with no spaces. THIS IS MY PREFERRED FORMAT :).
dfuk['sub_region_1'] = dfuk['sub_region_1'].fillna('UK')
dfuk['subreg1'] = dfuk['sub_region_1'].astype('str').str.replace(' ','_')
dfuk
dfuk.to_csv(r'C:\Users\vw191\OneDrive\Documents\GitHub\107SBakst.github.io\data\uk_google_mobility.csv')

<ipython-input-70-d7f1ee4c6ddd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfuk['sub_region_1'] = dfuk['sub_region_1'].fillna('UK')
<ipython-input-70-d7f1ee4c6ddd>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfuk['subreg1'] = dfuk['sub_region_1'].astype('str').str.replace(' ','_')

In [71]:
dfuk['sub_region_2'] = dfuk['sub_region_2'].fillna('blank')
dfuk[(dfuk['subreg1']=='Greater_London') & (dfuk['sub_region_2'] == 'blank')].sort_values('date',ascending=False).head()

<ipython-input-71-c2ff7cdcb387>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfuk['sub_region_2'] = dfuk['sub_region_2'].fillna('blank')

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,subreg1
3165311,GB,United Kingdom,Greater London,blank,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2022-01-11,-38.0,-12.0,-24.0,-49.0,-43.0,15.0,Greater_London
3165310,GB,United Kingdom,Greater London,blank,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2022-01-10,-34.0,-8.0,-10.0,-48.0,-43.0,15.0,Greater_London
3165309,GB,United Kingdom,Greater London,blank,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2022-01-09,-28.0,-13.0,6.0,-38.0,-9.0,5.0,Greater_London
3165308,GB,United Kingdom,Greater London,blank,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2022-01-08,-41.0,-20.0,-52.0,-45.0,-15.0,9.0,Greater_London
3165307,GB,United Kingdom,Greater London,blank,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2022-01-07,-40.0,-11.0,-27.0,-51.0,-42.0,16.0,Greater_London